locale: "en"
lang: "en-us"
repository: marisavas/marisavas.github.io/teste_pagina
title: "Marisa Vasconcelos" # the name of your site, e.g. ACME Corp.
description: >- # this means to ignore newlines until "baseurl:"
   Marisa Vasconcelos site.
# domain: marisavas.github.io/teste_pagina
url: "https://marisavas.github.com"  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: "/teste_pagina" # the subpath of your site, e.g. /blog

permalink: '/:title/'


exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  
collections:
  pages:
    output: true
    permalink: /:path/

plugins:
  - jekyll-scholar

scholar:
  style: _bibliography/springer-lecture-notes-in-computer-science2.csl
  bibliography: "bibliography/sample.bib"
  repository: /publications
  locale: en
  # source: ./_bibliography
  bibliography_template: bib
  query: "@*"
  sort_by: year, month
  order: descending, descending
  replace_strings: true
  join_strings: true


font-awesome:
  assets: true

sass:
  sass_dir: _sass
  style: compressed

 