repository: marisavas/marisavas.github.io/teste_pagina
baseurl: "" # the subpath of your site, e.g. /blog
title: "Marisa Vasconcelos" # the name of your site, e.g. ACME Corp.
description: >- # this means to ignore newlines until "baseurl:"
   Marisa Vasconcelos site.
domain: marisavas.github.io/teste_pagina
url: https://marisavas.github.io/teste_pagina  # the base hostname and protocol for your site, e.g. http://example.com

permalink: '/:title/'




plugins:
  - jekyll-scholar

# baseurl: "" # the subpath of your site, e.g. /blog

scholar:
  bibliography: "bibliography/sample.bib"

font-awesome:
  assets: true

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor



  # scholar:
  #   style: _bibliography/springer-lecture-notes-in-computer-science2.csl
  #   locale: en
  #   source: ./_bibliography
  #   bibliography_template: bib
  #   query: "@*"
  #   sort_by: year, month
  #   order: descending, descending
  #   # group_by: none
  #   # group_order: descending
  #   repository: /publications
  #   replace_strings: true
  #   join_strings: true
